name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:21.04
    steps:
    - name: Install libarchive dependencies
      run: sudo apt-get update; sudo apt-get install libarchive-dev
    - name: Install gtk4 dependencies
      run: sudo apt install libgtk-4-dev build-essential
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
