name: Windows build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gtk4 mingw-w64-x86_64-libarchive
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-gnu
          profile: minimal
          override: true
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Check build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
